version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    depends_on: 
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_NODE_PORT: 5672
    ports:
      - 5672:5672
      - 15672:15672


  # elasticsearch:
  #   image: mdslino/elasticsearch:7.1.1
  #   container_name: chat-api-elasticsearch
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata01:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  # kibana:
  #   container_name: chat-api-kibana
  #   image: docker.elastic.co/kibana/kibana:7.1.1
  #   environment:
  #     ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - 5601:5601

  # flower:
  #   container_name: flower
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile
  #   environment:
  #     ROOT_PATH_FOR_DYNACONF: /app/conf/
  #     ENV_FOR_DYNACONF: default
  #   command: sh -c "python ./scripts/wait_for_services.py && celery -A chat-api.tasks.app flower --port=5555"
  #   ports:
  #     - "5555:5555"

volumes:
  mongodbdata:
    driver: local